name: 🤖 Generate Changelog and Versions

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: ⚡ Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/config/.release-please-config.json
          manifest-file: .github/config/.release-please-manifest.json
          target-branch: 'dev'
